### ISSUE TITLE
Error scraping for tablespace _ map No metrics found while parsing" source="main.go:236"

### ISSUE THREAD

**Issue by feiwenyuu** [iamseth/oracledb_exporter#134] opened 2020-09-15 09:36 UTC
When I use default-metrics.toml to query for tablespace metrics, this error is always displayed if there are too many table Spaces on Oracle, and can be normally checked if there are too few tableSpaces,Manually executing SQL query tablespace metrics in Oracle is succeed.

level=error msg="Error scraping for tablespace _ map[bytes:Generic counter metric of tablespaces bytes in Oracle. free:Generic counter metric of tablespaces free bytes in Oracle. max_bytes:Generic counter metric of tablespaces max bytes in Oracle.] : No metrics found while parsing" source="main.go:236"

**Comment by Yannig** [comment] 2020-09-15 14:23
Can you run the query with debug level?

**Comment by feiwenyuu** [comment] 2020-09-16 01:00
Yes, the log is now debug level, and the log only shows the error above

**Comment by feiwenyuu** [comment] 2020-09-16 01:05
I execute SQL directly on Oracle, which has a lot of table Spaces, and I wait 1-2 seconds, I don't know if it is Exporter that is timed out

**Comment by feiwenyuu** [comment] 2020-09-16 01:10
level=debug msg="Calling function ScrapeGenericValues()" source="main.go:264"
level=debug msg="ScrapeGenericValues() - metricsCount:  0" source="main.go:313"
level=error msg="Error scraping for tablespace _ map[bytes:Generic counter metric of tablespaces bytes in Oracle. free:Generic counter metric of tablespaces free bytes in Oracle. max_bytes:Generic counter metric of tablespaces max bytes in Oracle.] : No metrics found while parsing" source="main.go:236"

**Comment by Pilo11** [comment] 2020-09-16 06:18
I have exactly the same problem. Maybe it's useful to debug the GoLang code directly in GoLand or VS Code to investigate the problem.

**Comment by Yannig** [comment] 2020-09-17 06:36
When you have the problem, can you run the query directly on your database and give me back the result?

**Comment by Pilo11** [comment] 2020-09-17 07:49
> When you have the problem, can you run the query directly on your database and give me back the result?

Yes, of course. I think it has something to do with the NULL value
`SF_HIST_TBL	PERMANENT	135814676480	137437855744	20704395264
SYSAUX	PERMANENT	25559040000	34359721984	1109000192
SYSTEM	PERMANENT	901775360	34359721984	271777792
TEMP	TEMPORARY	34358689792	34359721984	34357641216
TS_DATA	PERMANENT	386815344640	410169196544	13728088064
TS_SDC_BACKSYNC_LOB	PERMANENT	5473566720	39728431104	1298006016
TS_SDC_RAW_LOB	PERMANENT	98784231424	98784231424	18340577280
TS_SDC_RAW_TAB	PERMANENT	21579694080	55834558464	12139364352
TS_SDC_TAB	PERMANENT	35316039680	55834558464	7750811648
UNDOTBS1	UNDO	34340864000	34359721984	
UNDOTBS2	UNDO	68719476736	35184372064256	51249676288`

**Comment by feiwenyuu** [comment] 2020-09-17 08:08
Without finding a solution, I tried to replace the image with iamseth/oracledb_exporter:0.2.9 and finally solved the problem.

**Comment by Pilo11** [comment] 2020-09-17 08:34
> Without finding a solution, I tried to replace the image with iamseth/oracledb_exporter:0.2.9 and finally solved the problem.

I can confirm that the 0.2.9 version is working for me, too.

**Comment by Pilo11** [comment] 2020-09-17 08:42
The old select in default-metrics.toml doesn't return any NULL values. It think that's the reason...

[old SQL query](https://github.com/iamseth/oracledb_exporter/commit/c52094761d245e64ec50407a83dd92039d30b759#diff-6be9231ba615fca2c6a1bdf5099c3b14)

![image](https://user-images.githubusercontent.com/10966593/93447284-88ca4780-f8d2-11ea-82a7-f2998297d981.png)

**Comment by feiwenyuu** [comment] 2020-09-17 09:06
You should check the SQL in default-metrics.toml

**Comment by Yannig** [comment] 2020-09-17 17:51
From my point of view, we can consider the NULL value as 0 (Zero).
I think we just have to modify the request.

**Comment by Yannig** [comment] 2020-09-18 05:45
PR merged.

Thanks for your contribution!

**Comment by Pilo11** [comment] 2020-09-18 08:19
Never sell the bear's skin before one has killed the beast ^^

I tried the new docker:latest version with the NVL changes in the SQL request (default-metrics.toml) but the same exception was catched...

`level=error msg="Error scraping for tablespace _ map[bytes:Generic counter metric of tablespaces bytes in Oracle. free:Generic counter metric of tablespaces free bytes in Oracle. max_bytes:Generic counter metric of tablespaces max bytes in Oracle.] : No metrics found while parsing" source="main.go:244"`

Very confusing. I think I have to investigate further...

**Comment by Yannig** [comment] 2020-09-18 12:04
No problem. Let me know when you have something that's working.

**Comment by Pilo11** [comment] 2020-10-30 09:33
I'm very sorry. I don't have the time to figure out what's goin' on, so I just replaced the SQL query with my own with some advantages.

I created a custom-metrics.toml with the following SQL statement.

`[[metric]]
context = "tablespace"
labels = [ "tablespace", "type" ]
metricsdesc = { bytes = "Generic counter metric of tablespaces bytes in Oracle.", max_bytes = "Generic counter metric of tablespaces max bytes in Oracle.", free = "Generic counter metric of tablespaces free bytes in Oracle." }
request = '''
select
    tbl.tablespace_name tablespace,
    NVL(tbl.type,'') type,
    NVL(sum(tbl.allocated_mb),0) bytes,
    NVL(sum(tbl.capacity),0) max_bytes,
    NVL(sum(tbl.free),0) free
from (
    with tablespace_data as (
        SELECT file_id, file_name,
                tablespace_name,
                autoextensible,
                bytes,
                decode(autoextensible,'YES',maxbytes,bytes) maxsize
         FROM   dba_data_files
         GROUP BY file_id, file_name,
                  tablespace_name,
                  autoextensible,
                  bytes,
                  decode(autoextensible,'YES',maxbytes,bytes)
    ), tablespace_files as (
        SELECT file_id,
                 tablespace_name,
                 sum(bytes) free
          FROM   dba_free_space
          GROUP BY file_id,
                   tablespace_name
    )
    SELECT substr(tbld.tablespace_name,1,14) tablespace_name,
           decode(tbld.autoextensible,'YES',tbld.MAXSIZE-tbld.bytes+tblf.free,'NO',tblf.free) free,
           tbld.bytes allocated_mb,
           tbld.MAXSIZE capacity,
           dt.contents type
    FROM tablespace_data tbld
    left join tablespace_files tblf on (tbld.FILE_ID = tblf.FILE_ID and tbld.tablespace_name = tblf.tablespace_name)
    left join dba_tablespaces dt on dt.tablespace_name = tbld.tablespace_name
) tbl
group by tbl.tablespace_name,
    tbl.type
'''`

This command reads the real left space on tablespaces because it considers the auto extend tablespaces which are f.e. using 10G of 30G but will extend to 20G when it needed. So now I have the real left tablespace values for my databases.

**Closed** 2020-12-06 16:52 UTC
Labels: bug
