### ISSUE TITLE
New Docker Image iamseth/oracledb_exporter:latest Not Picking metrics.tolm File

### ISSUE THREAD

**Issue by frankYaohua** [iamseth/oracledb_exporter#94] opened 2020-04-14 22:33 UTC
I override the default-metrics file by having the DockerFile like:
ENTRYPOINT ["/oracledb_exporter", "-default.metrics", "/default-metrics.toml", "-query.timeout", "60"]

But, I checked the metrics. Seems like, the exporter does not pick up the default-metrics file. No exposed metrics found in http://localhost:9161/metrics.

I tried the 0.2.6, it works perfectly fine, but not the latest one (0.2.7).

Thanks!

**Comment by Yannig** [comment] 2020-04-15 12:37
Can you try to do the same by using DEFAULT_METRICS env variable?

**Comment by frankYaohua** [comment] 2020-04-20 23:38
Seems, still not working. I am passing two Env variables like this:
docker ... -e 'DATA_SOURCE_NAME=...' -e 'DEFAULT_METRICS=./default-metrics.toml' ...
Still no metrics are picking up by the Exporter.
Thanks!

**Comment by Yannig** [comment] 2020-04-21 07:36
Here you are using a relative path. Can you try to use the complete path (/where/my/file/belongs/default-metrics.toml).

**Comment by voskampm** [comment] 2020-04-21 07:41
I have the same problem. Tried DEFAULT_METRICS with an absolute path:

-bash-4.2$ export DEFAULT_METRICS=/etc/default/default-metrics.toml
-bash-4.2$ /opt/prometheus/exporters/oracledb_exporter -log.level debug -web.listen-address localhost:9161
INFO[0000] Starting oracledb_exporter 0.2.7              source=main.go:347
ERRO[0003] Error scraping for database : No metrics found while parsing  source=main.go:198
INFO[0021] Listening on localhost:9161                   source=main.go:369

regards, Michiel

**Comment by Yannig** [comment] 2020-04-21 09:00
Can you share your Docker repo or can you try to reproduce it on a repos where I can have access?

**Comment by voskampm** [comment] 2020-04-22 12:51
>> Can you share your git Docker repo or can you try to reproduce it on a repos where I can have access?

Do you need my .toml file? The rest of the code and configuration is unchanged (version 0.2.7) except that I compiled the code against an Oracle 19.3 client.

I have added some debug statements to the application (See https://github.com/iamseth/oracledb_exporter/pull/97). 
I then start the exporter with:
```
-bash-4.2$ export ORACLE_HOME=/u01/app/oracle/product/19.3/dbhome_1; export LD_LIBRARY_PATH=$ORACLE_HOME/lib; export ORACLE_SID=cdb1; ORACLE_BIN=$ORACLE_HOME/bin; export TNS_ADMIN=/u01/app/oracle/product/19.3/dbhome_1/network/admin; cd $ORACLE_BIN; export DATA_SOURCE_NAME=c##ordprm/password@//localhost:1521/cdb1;
-bash-4.2$ /vagrant/oracledb_exporter -log.level debug -web.listen-address localhost:9161 -default.metrics /etc/default/default-metrics.toml 

```
What is see is that the .toml is used and the queries in the .toml are run successfully against Oracle. The last line I get is: 
> INFO[0019] Listening on localhost:9161                   source=main.go:402

and then nothing much happens in the logging even if I scrape the exporter. 

Scraping results:
```
curl -sS localhost:9161/metrics | grep -v ^#
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
go_goroutines 10
go_info{version="go1.14.2"} 1
go_memstats_alloc_bytes 1.368824e+06
go_memstats_alloc_bytes_total 1.368824e+06
go_memstats_buck_hash_sys_bytes 1.444401e+06
go_memstats_frees_total 1294
go_memstats_gc_cpu_fraction 0
go_memstats_gc_sys_bytes 3.436808e+06
go_memstats_heap_alloc_bytes 1.368824e+06
go_memstats_heap_idle_bytes 6.4339968e+07
go_memstats_heap_inuse_bytes 2.37568e+06
go_memstats_heap_objects 11546
go_memstats_heap_released_bytes 6.4339968e+07
go_memstats_heap_sys_bytes 6.6715648e+07
go_memstats_last_gc_time_seconds 0
go_memstats_lookups_total 0
go_memstats_mallocs_total 12840
go_memstats_mcache_inuse_bytes 3472
go_memstats_mcache_sys_bytes 16384
go_memstats_mspan_inuse_bytes 36856
go_memstats_mspan_sys_bytes 49152
go_memstats_next_gc_bytes 4.473924e+06
go_memstats_other_sys_bytes 771527
go_memstats_stack_inuse_bytes 393216
go_memstats_stack_sys_bytes 393216
go_memstats_sys_bytes 7.2827136e+07
go_threads 7
process_cpu_seconds_total 0.3
process_max_fds 4096
process_open_fds 13
process_resident_memory_bytes 2.154496e+07
process_start_time_seconds 1.58754193062e+09
process_virtual_memory_bytes 1.086468096e+09
process_virtual_memory_max_bytes -1
promhttp_metric_handler_requests_in_flight 1
promhttp_metric_handler_requests_total{code="200"} 0
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
debug logging 
```
INFO[0000] Starting oracledb_exporter 0.2.7              source=main.go:373
INFO[0000] Successfully loaded default metrics from: /etc/default/default-metrics.toml  source=main.go:380
INFO[0000] No custom metrics defined.                    source=main.go:394
DEBU[0000] Successfully connected to:  c##ordprm/password@//localhost:1521/cdb1  source=main.go:93
DEBU[0001] Successfully pinged Oracle database:          source=main.go:194
DEBU[0001] About to scrape metric:                       source=main.go:199
DEBU[0001] - Metric MetricsDesc:  map[uptime_seconds:Number of days since the last database shutdown.]  source=main.go:200
DEBU[0001] - Metric Context:  database                   source=main.go:201
DEBU[0001] - Metric MetricsType:  map[uptime_seconds:counter]  source=main.go:202
DEBU[0001] - Metric Labels:  []                          source=main.go:203
DEBU[0001] - Metric FieldToAppend:                       source=main.go:204
DEBU[0001] - Metric IgnoreZeroResult:  false             source=main.go:205
DEBU[0001] - Metric Request:  select (sysdate - startup_time)*86400 as uptime_seconds from v$instance  source=main.go:206
DEBU[0001] Calling function ScrapeGenericValues()        source=main.go:247
DEBU[0001] Query result looks like:  189939              source=main.go:273
DEBU[0002] ScrapeGenericValues() - metricsCount:  1      source=main.go:296
DEBU[0002] Successfully scrapped metric:  database       source=main.go:222
DEBU[0002] About to scrape metric:                       source=main.go:199
DEBU[0002] - Metric MetricsDesc:  map[version:version]   source=main.go:200
DEBU[0002] - Metric Context:  database                   source=main.go:201
DEBU[0002] - Metric MetricsType:  map[version:counter]   source=main.go:202
DEBU[0002] - Metric Labels:  []                          source=main.go:203
DEBU[0002] - Metric FieldToAppend:                       source=main.go:204
DEBU[0002] - Metric IgnoreZeroResult:  false             source=main.go:205
DEBU[0002] - Metric Request:  select regexp_replace((regexp_substr(banner_full,'[^Production version]+$')),'[^0-9]','') as version from v$version  source=main.go:206
DEBU[0002] Calling function ScrapeGenericValues()        source=main.go:247
DEBU[0002] Query result looks like:  193000              source=main.go:273
DEBU[0003] ScrapeGenericValues() - metricsCount:  1      source=main.go:296
DEBU[0003] Successfully scrapped metric:  database       source=main.go:222
INFO[0003] Listening on localhost:9161                   source=main.go:402
```

@frankYaohua: Do you see the same behaviour?

**Comment by Yannig** [comment] 2020-04-22 13:36
I saw the following export on your command line:

```export DATA_SOURCE_NAME=c##ordprm/password@//localhost:1521/cdb1;```

I think the '#' might be taken for a starting comment. Can you protect it like this:

```export DATA_SOURCE_NAME="c##ordprm/password@//localhost:1521/cdb1"```

**Comment by voskampm** [comment] 2020-04-22 17:45
Unfortunately no change in behavior.

```
-bash-4.2$ export ORACLE_HOME=/u01/app/oracle/product/19.3/dbhome_1; export LD_LIBRARY_PATH=$ORACLE_HOME/lib; export ORACLE_SID=cdb1; ORACLE_BIN=$ORACLE_HOME/bin; export TNS_ADMIN=/u01/app/oracle/product/19.3/dbhome_1/network/admin; cd $ORACLE_BIN; export DATA_SOURCE_NAME="c##ordprm/password@//localhost:1521/cdb1";
-bash-4.2$ /vagrant/oracledb_exporter -log.level debug -web.listen-address localhost:9161 -default.metrics /etc/default/default-metrics.toml 
INFO[0000] Starting oracledb_exporter 0.2.7              source=main.go:373
INFO[0000] Successfully loaded default metrics from: /etc/default/default-metrics.toml  source=main.go:380
INFO[0000] No custom metrics defined.                    source=main.go:394
DEBU[0000] Successfully connected to:  c##ordprm/password@//localhost:1521/cdb1  source=main.go:93
DEBU[0002] Successfully pinged Oracle database:          source=main.go:194
DEBU[0002] About to scrape metric:                       source=main.go:199
DEBU[0002] - Metric MetricsDesc:  map[uptime_seconds:Number of days since the last database shutdown.]  source=main.go:200
DEBU[0002] - Metric Context:  database                   source=main.go:201
DEBU[0002] - Metric MetricsType:  map[uptime_seconds:counter]  source=main.go:202
DEBU[0002] - Metric Labels:  []                          source=main.go:203
DEBU[0002] - Metric FieldToAppend:                       source=main.go:204
DEBU[0002] - Metric IgnoreZeroResult:  false             source=main.go:205
DEBU[0002] - Metric Request:  select (sysdate - startup_time)*86400 as uptime_seconds from v$instance  source=main.go:206
DEBU[0002] Calling function ScrapeGenericValues()        source=main.go:247
DEBU[0002] Query result looks like:  207439              source=main.go:273
DEBU[0003] ScrapeGenericValues() - metricsCount:  1      source=main.go:296
DEBU[0003] Successfully scrapped metric:  database       source=main.go:222
DEBU[0003] About to scrape metric:                       source=main.go:199
DEBU[0003] - Metric MetricsDesc:  map[version:version]   source=main.go:200
DEBU[0003] - Metric Context:  database                   source=main.go:201
DEBU[0003] - Metric MetricsType:  map[version:counter]   source=main.go:202
DEBU[0003] - Metric Labels:  []                          source=main.go:203
DEBU[0003] - Metric FieldToAppend:                       source=main.go:204
DEBU[0003] - Metric IgnoreZeroResult:  false             source=main.go:205
DEBU[0003] - Metric Request:  select regexp_replace((regexp_substr(banner_full,'[^Production version]+$')),'[^0-9]','') as version from v$version  source=main.go:206
DEBU[0003] Calling function ScrapeGenericValues()        source=main.go:247
DEBU[0003] Query result looks like:  193000              source=main.go:273
DEBU[0004] ScrapeGenericValues() - metricsCount:  1      source=main.go:296
DEBU[0004] Successfully scrapped metric:  database       source=main.go:222
INFO[0004] Listening on localhost:9161                   source=main.go:402
```

**Comment by frankYaohua** [comment] 2020-04-23 02:27
@voskampm same behavior for me "nothing much happens in the logging even if I scrape the exporter."
I basically just changed the docker image version from an old version to the latest one, then metrics are not picking up.

**Comment by kevinqmcdonald** [comment] 2020-04-23 14:36
@voskampm @frankYaohua I was running into the same issue and only was able to scrape the default oracledb metrics once i downgraded my image to version 0.2.6a

**Comment by voskampm** [comment] 2020-04-24 10:18
I have investigated the changes between 0.2.7 and 0.2.6a. In the Dockerfile golang was updated from 1.11 to 1.14. I compiled the oracledb_exporter against golang 1.11. Compile was successfull but  the problem was not solved: No metrics from the default-metrics.toml file. 

My guess is that the problem is caused by one of the changes in: 0ab8aecf18ae23c65da2fdb98908b8067ed80b10. Unfortunately  that commit contains a lot of whitespace changes and it's hard to determine what actually changed. One of the things I did notice is that promhttp is added. I have no idea how to debug that library.

**Comment by Yannig** [comment] 2020-04-24 13:36
@voskampm I think the only difference came from this line:

```golang
http.Handle(*metricPath, promhttp.Handler())
```
Was `http.Handle(*metricPath, prometheus.Handler())`.

**Comment by voskampm** [comment] 2020-04-24 17:59
@Yannig: Reverting back to ```http.Handle(*metricPath, prometheus.Handler())``` solves the problem for me.

**Comment by frankYaohua** [comment] 2020-04-24 23:28
I tested it locally with the latest change (promhttp.Handler()), it works fine (go get latest libraries e.g. github.com/prometheus/client_golang), it can pick up the default metrics, but it's still not working with the latest Docker image (0.2.7). 

Is it the problem when pushing to docker? Like environment and dependency version? Library like: github.com/prometheus/client_golang/prometheus/promhttp?

Thanks!

**Comment by arcshiftsolutions** [comment] 2020-04-24 23:29
Our team is having the same issue but with custom queries. Totally fine with the 0.2.6a image but with 0.2.7 we see no oracle specific metrics.

**Comment by Yannig** [comment] 2020-04-25 17:33
I managed to reproduce the problem on my computer.
The problem seems to be a regression with recent versions of Prometheus libraries.
I'll try to fix that.

**Comment by Yannig** [comment] 2020-04-25 17:57
I think the problem is fixed on master branch.
Is it possible to check if everything is ok now?

**Comment by Yannig** [comment] 2020-04-28 05:53
The last release include a fix for this problem.
https://github.com/iamseth/oracledb_exporter/releases/tag/0.2.8

**Comment by binoy351** [comment] 2020-04-28 13:07
> The last release include a fix for this problem.
> https://github.com/iamseth/oracledb_exporter/releases/tag/0.2.8

The latest release works fine. I am able to collect the required metrics.

**Closed** 2020-04-28 18:39 UTC
Labels: bug

**Comment by frankYaohua** [comment] 2020-04-28 20:06
Thanks Yannig!
