### ISSUE TITLE
Encoding issues? Question marks instead of cyrillic letters

### ISSUE THREAD

**Issue by ILyaCyclone** [iamseth/oracledb_exporter#120] opened 2020-08-08 07:42 UTC
Using docker image iamseth/oracledb_exporter:latest with adding custom_metrics.toml file.

Result of custom query in toml file are some metrics together with ID_KIND and KIND_NAME as labels. KIND_NAME contains cyrillic letters.  
On runtime docker container and exporter work fine as whole but in browser on /metrics instead of cyrillic letters I'm getting questions marks. Seems like encoding issue. And I can't find any configuration point about that.  
Setting encoding in browser does not solve the issue, so I believe it's somewhere deeper.

Screenshot: https://prnt.sc/tw4h5x

---------------------

Reproducible with following custom-metrics.toml entry:

```
[[metric]]
context = "cyrillic_test"
labels = ["cyrillic_letters"]
request = """
select 1 as val, 'кириллические символы 1' as cyrillic_letters from dual
union all
select 2 as val, 'кириллические символы 2' as cyrillic_letters from dual
"""
metricsdesc = { val = "Dummy value for cyrillic letters display" }
```
leads to following result on /metrics:

```
# HELP oracledb_cyrillic_test_val Dummy value for cyrillic letters display
# TYPE oracledb_cyrillic_test_val gauge
oracledb_cyrillic_test_val{cyrillic_letters="?????????????????????????? ?????????????? 1"} 1
oracledb_cyrillic_test_val{cyrillic_letters="?????????????????????????? ?????????????? 2"} 2
```

Even though writing cyrillic letters directly in toml file might cause additional encoding issues on the way, so those letters better be written in table for clearer testcase.

**Comment by Yannig** [comment] 2020-10-09 07:40
I'm not able to reproduce this problem on my setup.
I'm wondering if this issue might have been fixed in last version with updated dependencies.

**Closed** 2020-10-09 07:42 UTC
Labels: bug
