### ISSUE TITLE
Increasing use of memory when running exporter on standby db

### ISSUE THREAD

**Issue by patrickschilderING** [iamseth/oracledb_exporter#52] opened 2019-08-29 15:33 UTC
In our environment (linux) we are using oracle with one active db and one standby.
What we are seeing when running the exporter on the standby machine, is that the exporter is consuming more and more memory. 
Eventually the memory consumption will go up to 80%.

ERRO[1477] Error pinging oracle: ORA-01033: ORACLE initialization or shutdown in progress
source=main.go:168
INFO[1477] Try to reconnect... source=main.go:171
ERRO[1477] Unable to connect to oracle:ORA-01033: ORACLE initialization or shutdown in progress
source=main.go:179

I'm using Oracle instant client 12.2

On the active db the exporter is behaving normally and stays around 0.1 / 0.2 %

I ran a build using the latest version of the code.

**Comment by patrickschilderING** [comment] 2019-09-03 08:06
Today i debugged with pprof, it was showing me the following results:

Showing nodes accounting for 253.87MB, 95.61% of 265.51MB total
Dropped 25 nodes (cum <= 1.33MB)
Showing top 10 nodes out of 57
      flat  flat%   sum%        cum   cum%
  193.03MB 72.70% 72.70%   227.22MB 85.58%  compress/flate.NewWriter
   32.05MB 12.07% 84.77%    32.05MB 12.07%  compress/flate.(*compressor).initDeflate
    6.57MB  2.48% 87.25%   233.90MB 88.09%  github.com/prometheus/client_golang/prometheus.(*registry).writePB
    5.65MB  2.13% 89.38%     5.65MB  2.13%  regexp.(*bitState).reset
    4.02MB  1.51% 90.89%     4.02MB  1.51%  os.(*File).readdirnames
    3.02MB  1.14% 92.03%     3.02MB  1.14%  runtime/debug.ReadGCStats
    3.01MB  1.13% 93.16%     3.01MB  1.13%  bufio.(*Scanner).Scan
    3.01MB  1.13% 94.29%     3.01MB  1.13%  compress/flate.(*huffmanEncoder).generate
       2MB  0.75% 95.05%        2MB  0.75%  regexp.(*Regexp).FindAllStringIndex.func1
    1.51MB  0.57% 95.61%     6.02MB  2.27%  github.com/prometheus/client_golang/prometheus.(*goCollector).Collect

**Comment by patrickschilderING** [comment] 2019-09-05 16:06
I also see the number of goroutines going up to 95000 after a couple of hours scraping.

**Comment by Yannig** [comment] 2019-09-06 14:30
Hi,

Can you try to compile last version and see if the problem is solved?

Regards

**Comment by patrickschilderING** [comment] 2019-09-13 12:48
I am using the latest version. It's only happening on the oracle standby server, hot server is not giving any problems.

**Comment by Yannig** [comment] 2019-09-13 20:49
I was talking about the last version in git. Can you try to compile it?

If it's not the case, let me know.

**Comment by Yannig** [comment] 2019-09-14 11:30
Can you try with this binary:

https://github.com/iamseth/oracledb_exporter/releases/download/0.2.3/oracledb_exporter.0.2.3.linux-amd64.tar.gz

**Comment by patrickschilderING** [comment] 2019-09-18 07:13
I got the following error:
error while loading shared libraries: libclntsh.so.18.1:

I'm using oracle instant client version 12.2

**Comment by patrickschilderING** [comment] 2019-09-18 14:13
I also tried with your change to close DB connection before trying to reconnect.

But looking at the pprof analysis it looks like the memory leak is coming from:
193.03MB 72.70% 72.70% 227.22MB 85.58% compress/**flate.NewWriter**
32.05MB 12.07% 84.77% 32.05MB 12.07% compress/flate.(*compressor).initDeflate
6.57MB 2.48% 87.25% 233.90MB 88.09% github.com/prometheus/client_golang/prometheus.**(*registry).writePB**

**Comment by djpasch** [comment] 2019-09-24 08:22
I finally found out the issue, there were actually more than one.
I will commit my changes and create a pull request.

**Comment by patrickschilderING** [comment] 2019-09-24 11:48
https://github.com/iamseth/oracledb_exporter/pull/56

**Comment by Yannig** [comment] 2019-11-02 08:38
@patrickschilderING I have merged your work and I'm working on a way to release multiple versions of the exporter to handle multiple Oracle versions.

**Closed by Yannig** 2019-11-02 08:38 UTC
Labels: bug
